fix(widget)!: List should not ignore empty string items
tui-rs-revival/tui-rs-revival pull request #42
Opened 2023-02-12 22:07 UTC by orhun

> Upstream: [#688](https://github.com/fdehau/tui-rs/pull/688)

## Description
Fixes issue [#680](https://github.com/fdehau/tui-rs/issues/680#issue-1462518032). Handles the case where a list item is created with an empty string, which is not split by the `lines` iterator.

## Testing guidelines
New test can be ran with `cargo test`

## Checklist

* [x] I have read the [contributing guidelines](../CONTRIBUTING.md).
* [x] I have added relevant tests.
* [x] I have documented all new additions.

2023-02-14 16:24 UTC, sayanarijit requested changes

2023-02-14 16:24 UTC, sayanarijit commented on src/text.rs
> +            lines: if lines.len() == 0 {
```suggestion
            lines: if lines.is_empty() {
```

2023-02-16 15:34 UTC, mindoodoo approved these changes

2023-02-17 05:21 UTC, rhysd commented
This branch needs to be rebased on the latest main branch so that newer version of Rust compiler will be used and it will fix the issue on compiling `cargo-make` crate.

2023-02-17 12:00 UTC, orhun commented
Rebased.

2023-02-17 12:23 UTC, rhysd approved these changes

2023-02-17 13:10 UTC, sayanarijit requested changes
Please hold this, I think I missed to see this, it can be improved. is_empty() should be done in the input string.

2023-02-17 15:06 UTC, sayanarijit commented
Updated.

2023-02-17 15:08 UTC, sayanarijit commented
But this looks like a breaking change. Some users might be using this bug/feature as a condition, So, let's wait for a major release?

2023-02-17 16:38 UTC, sayanarijit commented
Ah, good point.

2023-02-17 16:38 UTC, sayanarijit approved these changes

2023-02-18 10:20 UTC, mindoodoo approved these changes

2023-02-21 12:22 UTC, merged